---

inherit_gem:
  rubocop-sensible: 'config/rubocop.yml'

require:
  - rubocop-performance

AllCops:
  Exclude:
    - 'Rakefile'
    - 'alba.gemspec'

Layout/SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space

Metrics/MethodLength:
  Max: 20

Style/FrozenStringLiteralComment:
  Enabled: false
