---

inherit_gem:
  rubocop-sensible: 'config/rubocop.yml'

require:
  - rubocop-minitest
  - rubocop-performance

AllCops:
  Exclude:
    - 'Rakefile'
    - 'alba.gemspec'
  NewCops: enable

Layout/ClassStructure:
  Enabled: true

Layout/SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space

Metrics/ClassLength:
  Exclude:
    - 'test/alba_test.rb'

Metrics/MethodLength:
  Max: 20

Style/FrozenStringLiteralComment:
  Enabled: false
