---

inherit_gem:
  rubocop-sensible: 'config/rubocop.yml'

require:
  - rubocop-minitest
  - rubocop-performance

AllCops:
  Exclude:
    - 'Rakefile'
    - 'alba.gemspec'
  NewCops: enable
  EnabledByDefault: true

# Oneline comment is not valid so until it gets valid, we disable it
Bundler/GemComment:
  Enabled: false

Layout/ClassStructure:
  Enabled: true

Layout/SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space

Layout/MultilineAssignmentLayout:
  EnforcedStyle: same_line

Lint/ConstantResolution:
  Enabled: false

Metrics/ClassLength:
  Exclude:
    - 'test/alba_test.rb'

Metrics/MethodLength:
  Max: 15

Style/ConstantVisibility:
  Enabled: false

Style/Copyright:
  Enabled: false

Style/DocumentationMethod:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/InlineComment:
  Enabled: false

Style/MethodCallWithArgsParentheses:
  Enabled: false
