---

inherit_gem:
  rubocop-sensible: 'config/rubocop.yml'

require:
  - rubocop-minitest
  - rubocop-performance
  - rubocop-rake

AllCops:
  Exclude:
    - 'Rakefile'
    - 'alba.gemspec'
    - 'benchmark/**/*.rb'
  NewCops: enable
  EnabledByDefault: true
  TargetRubyVersion: 2.5

# Oneline comment is not valid so until it gets valid, we disable it
Bundler/GemComment:
  Enabled: false

Layout/SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space

Layout/MultilineAssignmentLayout:
  EnforcedStyle: same_line

Lint/ConstantResolution:
  Enabled: false

Metrics/ClassLength:
  Exclude:
    - 'test/alba_test.rb'

Metrics/MethodLength:
  Max: 15

# Resource class includes DSLs, which tend to accept long list of parameters
Metrics/ParameterLists:
  Exclude:
    - 'lib/alba/resource.rb'

# We need to eval resource code to test errors on resource classes
Security/Eval:
  Exclude:
    - 'test/**/*.rb'

Style/ConstantVisibility:
  Exclude:
    - 'lib/alba/version.rb'

Style/Copyright:
  Enabled: false

# I know what I do :)
Style/DisableCopsWithinSourceCodeDirective:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/InlineComment:
  Enabled: false

Style/MethodCallWithArgsParentheses:
  Enabled: false

# There are so many cases we just want `if` expression!
Style/MissingElse:
  EnforcedStyle: case
